############################
## CHANGE THESE
############################

baseURL: 'https://chawatvish.github.io'
title: 'CWStory.com'
theme: "qubt"

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'