############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 10
- name: Services
  url: /services/
  weight: 20
- name: Portfolio
  url: /portfolio/
  weight: 30
- name: About
  url: /about/
  weight: 40