############################
## Author
############################

author:
  name: "Chawatvish Worrapoj"
  image: author.jpg
  greeting: "A software engineer who passionate about mobile applications"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/chawatvish
  # - gitlab: 
  # - facebook: https://github.com/chrede88/qubt
  # - x-twitter:
  # - mastodon:
  - linkedin: http://linkedin.com/in/chawatvish/?ref=cwstory.com
  # - instagram: https://github.com/chrede88/L1nkr
  # - reddit: 
  # - telegram: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  - email: mailto:chawatvish.wo@gmail.com
  # - website: https://github.com/chrede88/qubt
  - link: https://fastwork.co/user/chawatvish/mobile-application-96557276?badges=&position=1&ref=cwstory.com
  # - discord:
  # - orcid:
  # - slack:
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud:
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube:
  # - keybase: 
  # - flickr: 
  # - tumblr:
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket:
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  - medium: https://chawatvish.medium.com 
  # - foursquare: 
  # - apple: 
  # - amazon: 
  # - google: 
  # - paypal: 
  # - windows: 

###############################
## OpenGraph & Twitter Cards
###############################

title: "CWStory.com"
description: "I am iOS developer who love to sharing my knowledge about iOS Android and Flutter application books self improvement and financial. Enjoy with my content"
images:
  - thumbnail.png